
import React from 'react';
import {
  Wrench,
  Flame,
  Umbrella,
  Zap,
  Trees,
  Hammer,
  Droplets,
  ShieldCheck,
  Paintbrush,
  Grid,
  Box
} from 'lucide-react';
import { Sector } from '@/types';

// Used for visual categorization in UI
export const CATEGORIES = [
  { id: 'plumbing', label: { EN: 'Plumbing', FR: 'Plomberie', NL: 'Loodgieterij' }, icon: <Droplets className="w-4 h-4" /> },
  { id: 'heating', label: { EN: 'Heating', FR: 'Chauffage', NL: 'Verwarming' }, icon: <Flame className="w-4 h-4" /> },
  { id: 'roofing', label: { EN: 'Roofing', FR: 'Toiture', NL: 'Dakbedekking' }, icon: <Umbrella className="w-4 h-4" /> },
  { id: 'electricity', label: { EN: 'Electricity', FR: 'Électricité', NL: 'Elektriciteit' }, icon: <Zap className="w-4 h-4" /> },
  { id: 'carpentry', label: { EN: 'Carpentry', FR: 'Menuiserie', NL: 'Timmerwerk' }, icon: <Trees className="w-4 h-4" /> },
  { id: 'masonry', label: { EN: 'Masonry', FR: 'Maçonnerie', NL: 'Metselwerk' }, icon: <Hammer className="w-4 h-4" /> },
  { id: 'waterproofing', label: { EN: 'Waterproofing', FR: 'Étanchéité', NL: 'Waterdichtheid' }, icon: <ShieldCheck className="w-4 h-4" /> },
  { id: 'other', label: { EN: 'Other', FR: 'Autre', NL: 'Ander' }, icon: <Wrench className="w-4 h-4" /> },
];

export const SECTORS: { id: Sector, label: { EN: string, FR: string, NL: string }, icon: React.ReactNode }[] = [
  { id: 'ELECTRICITE', label: { EN: 'Electricity', FR: 'Électricité', NL: 'Elektriciteit' }, icon: <Zap size={14} /> },
  { id: 'CARRELAGE', label: { EN: 'Tiling', FR: 'Carrelage', NL: 'Tegelwerk' }, icon: <Grid size={14} /> },
  { id: 'SANITAIRE', label: { EN: 'Sanitary', FR: 'Sanitaire', NL: 'Sanitair' }, icon: <Droplets size={14} /> },
  { id: 'CHAUFFAGE', label: { EN: 'Heating', FR: 'Chauffage', NL: 'Verwarming' }, icon: <Flame size={14} /> },
  { id: 'PLOMBERIE', label: { EN: 'Plumbing', FR: 'Plomberie', NL: 'Loodgieterij' }, icon: <Wrench size={14} /> },
  { id: 'PEINTURE', label: { EN: 'Painting', FR: 'Peinture', NL: 'Schilderwerk' }, icon: <Paintbrush size={14} /> },
  { id: 'MENUISERIE', label: { EN: 'Carpentry', FR: 'Menuiserie', NL: 'Timmerwerk' }, icon: <Trees size={14} /> },
  { id: 'GENERAL', label: { EN: 'General', FR: 'Général', NL: 'Algemeen' }, icon: <Box size={14} /> },
  { id: 'AUTRE', label: { EN: 'Other', FR: 'Autre', NL: 'Andere' }, icon: <Wrench size={14} /> },
];

export const URGENCY = [
  { id: 'LOW', label: { EN: 'Low', FR: 'Faible', NL: 'Laag' }, color: 'text-zinc-400' },
  { id: 'MEDIUM', label: { EN: 'Medium', FR: 'Moyenne', NL: 'Gemiddeld' }, color: 'text-blue-400' },
  { id: 'HIGH', label: { EN: 'High', FR: 'Haute', NL: 'Hoog' }, color: 'text-orange-400' },
  { id: 'CRITICAL', label: { EN: 'Critical', FR: 'Critique', NL: 'Kritiek' }, color: 'text-red-500' },
];


export const DELAY_REASONS = [
  { id: 'missing_part', EN: 'Missing part', FR: 'Pièce manquante', NL: 'Ontbrekend onderdeel' },
  { id: 'no_access', EN: 'No access', FR: 'Accès impossible', NL: 'Geen toegang' },
  { id: 'client_unavailable', EN: 'Client unavailable', FR: 'Client indisponible', NL: 'Klant niet beschikbaar' },
  { id: 'waiting_validation', EN: 'Waiting syndic validation', FR: 'En attente de validation du syndic', NL: 'Wachten op validatie syndicus' },
  { id: 'weather', EN: 'Bad weather', FR: 'Intempéries / météo', NL: 'Slecht weer' },
  { id: 'subcontractor', EN: 'Subcontractor unavailable', FR: 'Sous-traitant indisponible', NL: 'Onderaannemer niet beschikbaar' },
  { id: 'other', EN: 'Other', FR: 'Autre', NL: 'Andere' },
];

export const TRANSLATIONS = {
  EN: {
    // Reports Page
    reports_title: 'Intervention Reports',
    reports_subtitle: 'Consolidated view of all intervention slips and history.',
    latest_slips: 'Latest Intervention Slips',
    full_history: 'Full Intervention History',
    filter_status: 'Filter by Status',
    filter_all: 'All Statuses',
    filter_date_from: 'From',
    filter_date_to: 'To',
    search_placeholder: 'Search title, building, or address...',
    total: 'Total',
    load_more: 'Load More',
    no_interventions_yet: 'No interventions yet.',
    create_first: 'Create your first intervention',
    download_pdf: 'Download PDF',
    view: 'View',
    verify_docs: 'Review Documents',
    slip_id: 'Slip ID',
    created_at: 'Created At',

    // ... Existing translations ...
    period: 'Period',
    period_current_month: 'Current Month',
    period_3_months: 'Last 3 Months',
    period_6_months: 'Last 6 Months',
    period_current_year: 'Current Year',
    kpi_missions: 'Missions',
    kpi_ongoing: 'Ongoing',
    kpi_delayed: 'Delayed',
    kpi_completed: 'Completed',
    kpi_sectors: 'Interventions by sector',
    no_data_period: 'No interventions for this period.',
    interventions_received: 'Interventions Received',
    compare: 'Compare',
    current_period: 'Current period',
    previous_year: 'Previous year',
    overview_title: 'Overview',
    overview_subtitle: 'Key performance indicators.',
    delayTitle: 'Reason for delay',
    delayReasonLabel: 'Reason',
    delayDetailsLabel: 'Details (optional)',
    selectReason: 'Select a reason...',
    delayError: 'Please select a delay reason.',
    delayDetailsPlaceholder: 'Briefly explain the reason for the delay...',
    improveAI_text: 'Improve with AI',
    textImproved: 'Text improved',
    welcomeBack: 'Welcome back',
    manager: 'manager',
    activeSession: 'Active Session',
    logout: 'Sign out',
    logoutSystem: 'Logout System',
    account: 'Account',
    currentRole: 'Current Role',
    traceability: 'Traceability',
    enabled: 'Enabled',
    unassigned: 'Unassigned',
    missingInfo: 'Missing Information',
    dashboard: 'Dashboard',
    management: 'Management',
    ongoing: 'Ongoing Interventions',
    missions: 'Missions',
    missions_subtitle: 'Manage and track your building service requests',
    status_accepted: 'Accepted',
    status_rejected: 'Rejected',
    no_missions: 'No active missions.',
    no_pending: 'No pending requests.',
    no_accepted: 'No accepted missions yet.',
    no_rejected: 'No rejected missions.',
    reports: 'Reports',
    settings: 'Settings',
    help_tutorial: 'Help & Tutorial',

    information: 'Information',
    memberSince: 'Member since',
    statistiques: 'Statistics',
    properties: 'Properties',
    security: 'Security',
    privacy: 'Privacy',

    dash_short: 'Dash',
    emails_short: 'Emails',
    admin_short: 'Admin',

    language: 'Language',
    live: 'Live',
    proSelection: 'Professional',
    proSub: 'Manage interventions and propose missions.',
    syndicSelection: 'Syndic / Property Manager',
    syndicSub: 'Request interventions and track building assets.',
    clientSelection: 'Private Individual',
    clientSub: 'Track your building status and history.',
    adminEntry: 'Admin Entry',
    groupMgmt: 'Group Management',
    ecosystemDesc: 'The ultimate construction-industry ecosystem for professionals, syndics, and building owners.',
    subject: 'Subject',

    addBuilding: 'Add Building / Client',
    search: 'Search building, tenant, city, syndic...',
    cityOverview: 'Buildings by City',
    interventionHistory: 'Intervention History',
    createIntervention: 'Create Intervention',
    createMission: 'Mission Request',
    sendRequest: 'Send Request',
    createSyndic: 'Create Syndic',
    profile: 'Profile',
    needIntervention: 'Need an intervention?',
    createRequestDesc: 'Create a request in seconds and follow its progress in real time.',
    request: 'Request',
    myInterventions: 'My Interventions',

    planned: 'Missions',
    delayed: 'Delayed',
    completed: 'Completed',
    status_pending: 'In Progress',
    status_delayed: 'Delayed',
    status_completed: 'Completed',
    totalBuildings: 'Total Buildings',
    activePro: 'Active Professionals',
    improveAI: 'Improve with AI',
    optimizeAI: 'Optimize with AI',
    wait: 'Wait...',
    working: 'Working...',
    post: 'Post',
    approve: 'Approve',
    reject: 'Reject',
    save: 'Save',
    cancel: 'Cancel',
    upload: 'Upload Document',
    sign: 'Digital Signature',
    generateQR: 'Generate QR Code',
    back: 'Back',
    edit: 'Edit',
    modifier: 'MODIFY',
    details: 'Details',
    viewSlip: 'View Slip',
    validate: 'Validate',
    selectOrTypeAddress: 'Select or type address...',
    selectOrCreateSyndic: 'Select or create syndic...',
    interventionTitle: 'Intervention Title',
    receptionDate: 'Reception Date',
    requiredFields: 'Required fields',
    newBuildingAutoCreate: 'New building will be created',
    create: 'Create',
    sector: 'Sector / Category',
    selectSector: 'Select sector...',
    confirmDeleteTitle: 'Confirm deletion',
    confirmDeleteMsg: 'Are you sure you want to delete this item? This action is irreversible.',
    confirmDeleteMaintMsg: 'Are you sure you want to delete this maintenance plan?',
    btnDelete: 'Delete',
    btnCancel: 'Cancel',
    confirmRejectTitle: 'Confirm rejection',
    confirmRejectMsg: 'Are you sure you want to reject this mission? This action is irreversible.',
    btnReject: 'Reject mission',
    confirmApproveMsg: 'Are you sure you want to approve this mission?',
    interventionDateOptional: 'Intervention Date (optional)',
    missionLabel: 'Mission',
    tabs_data: 'Data',
    tabs_history: 'History',
    tabs_notes: 'Notes',
    tabs_plan: 'Plan',
    tabs_docs: 'Docs',
    select_date: 'Select Date',
    residentInfo: 'Resident Information',
    directContact: 'Direct Contact',
    linkedPro: 'Linked Professional',
    noneLinked: 'None linked',
    linkedSyndic: 'Linked Syndic',
    tenant: 'Tenant',
    primaryTenant: 'Primary Tenant',
    syndic: 'Syndic',
    pro: 'Professional',
    contact: 'Contact',
    email: 'Email',
    phone: 'Phone',
    managerName: 'Manager',
    postNote: 'Post Note',
    noCompletedInt: 'No completed interventions yet.',
    closedOn: 'Closed on',
    building_header: 'Building',
    scheduled_maintenance: 'Scheduled Maintenance',
    automatic_import: 'Automatic Import',
    newIntervention: 'New Intervention',
    category: 'Category',
    dateTime: 'Date & Time',
    autoNotify: 'Automatic notification will be sent to',
    hoursBefore: '72 hours before.',
    createPlan: 'Create & Plan',
    createMaintPlan: 'Create Maintenance Plan',
    updatePlan: 'Update Plan',
    saveMaintPlan: 'Save Maintenance Plan',
    maintTitle: 'Maintenance Title',
    smallDesc: 'Small Description',
    autoWeekBefore: 'Interventions will be created automatically 1 week before each due date.',
    planDuration: 'Plan Duration',
    scheduledFor: 'Scheduled for',
    unlimited: 'Unlimited',
    from: 'from',
    to: 'to',
    year_1: '1 year',
    years_2: '2 years',
    years_3: '3 years',
    years_5: '5 years',
    docRepo: 'Document Repository',
    ticketHeader: 'Intervention Slip',
    description: 'Intervention Description',
    adminNote: 'Admin Note',
    photos: 'Photos',
    docs: 'Documents',
    auditTrace: 'Audit Traceability',
    intInitialized: 'Intervention initialized on',
    updateStatus: 'Update Status',
    mediaAudit: 'Media & Audit',
    rescheduleDate: 'New estimated date',
    delayedUntil: 'Delayed until',
    saveRegister: 'REGISTER',
    saveModalTitle: 'Save Record',
    saveMode: 'Choose save mode',
    saveOnly: 'Save only',
    saveEmail: 'Save & send email',
    saveWhatsapp: 'Save & send WhatsApp',
    onSiteContactLabel: 'On-site contact',
    notProvided: 'Not provided',
    status: 'Status',
    autoEmailBadge: 'Created automatically from email',
    email_template_title: 'TITLE',
    email_template_status: 'STATUS',
    email_template_desc: 'DESCRIPTION',
    email_template_contact: 'CONTACT SUR PLACE',
    email_template_note: 'ADMIN NOTE',
    email_template_delay: 'DELAY REASON',
    email_template_new_date: 'NEW EST. DATE',
    email_template_footer: 'View details in the Vanakel Group application.',
    sendEmailError: 'Cannot send email: No valid recipients found.',
    sendWhatsappError: 'Cannot send WhatsApp: No phone number linked.',
    emailClientOpened: 'Email client opened.',
    mission_approved: 'Mission Approved',
    mission_rejected: 'Mission Rejected',
    manual_intervention_created: 'Manual Intervention Created',
    email_ingestion_mission: 'Mission Received via Email',
    status_change: 'Status Change',
    updated: 'Updated',
    maintenance_auto_title: 'Maintenance (Auto-generated)',
    manual_intervention_note: 'Created via manual intervention entry',
    auto_ingestion_note: 'Created automatically via email ingestion - Verify Syndic',
    editConfirmTitle: 'Edit Record',
    editConfirmDesc: 'Do you really want to edit an existing record?',
    yesEdit: 'Yes, edit',
    annualReport: 'Annual Report',
    downloadPDF: 'Download PDF',
    sendEmail: 'Send Email',
    aiSummary: 'AI Summary',
    annualMaintenance: 'Annual Maintenance',
    maintenance: 'Maintenance',
    frequency: 'Frequency',
    every: 'Every',
    years: 'years',
    months: 'months',
    unit_months: 'Months',
    unit_years: 'Years',
    startDate: 'Start Date',
    planDate: 'Plan Date',
    reviewSave: 'Review & Save',
    confirm: 'Confirm',
    planSummary: 'Maintenance Plan Summary',
    plannedDuration: 'Planned for the next 5 years',
    address: 'Address',
    city: 'City',
    tenants: 'Tenants',
    add: 'Add',
    firstName: 'First Name',
    lastName: 'Last Name',
    proLink: 'Professional Link',
    searchPro: 'Search Professional...',
    createNewPro: 'Create new Professional profile',
    syndicLink: 'Syndic Link',
    searchSyndic: 'Search Syndic...',
    createNewSyndic: 'Create new Syndic profile',
    internalNote: 'Internal Admin Note',
    createBuildingProfile: 'Create Building Profile',
    newProfileTitle: 'New Profile',
    companyName: 'Company Name',
    contactPerson: 'Contact Person',
    contactFirstName: 'First Name',
    contactLastName: 'Last Name',
    gsm: 'Mobile / GSM',
    mobileNumber: 'Mobile Number',
    landline: 'Landline',
    emailAddress: 'Email Address',
    businessAddress: 'Business Address',
    createProfile: 'Create Profile',
    contact_name: 'Name',
    contact_gsm: 'GSM / Tel',
    contact_email_opt: 'Email (Optional)',
    gestion_title: 'Management',
    gestion_subtitle: 'Overview of all properties with completed interventions.',
    all_syndics: 'All Syndics',
    no_properties_title: 'No properties found',
    no_properties_desc: 'No properties matched your filters or no completed interventions exist yet.',
    syndic_contact_title: 'Syndic Contact',
    no_syndic_linked: 'Not linked to a specific syndic.',
    history_title: 'Intervention History',
    no_history_found: 'No completed interventions record found for this property.',
    intervention_slip_doc: 'Intervention Slip',
    email_logs_title: 'Email Ingestion Logs',
    email_logs_empty: 'No email logs available yet. Trigger the ingestion job manually.',
    ingest_button_idle: 'Run Email Ingestion Job (Simulated)',
    ingest_button_working: 'Ingesting Emails...',
    extracted_data: 'Extracted Data',
    guide_welcome_title: 'Welcome to Vanakel Group',
    guide_welcome_desc: 'Your professional management ecosystem.',
    guide_nav_title: 'Navigation',
    guide_nav_desc: 'Access Dashboard, Buildings, and Missions here.',
    guide_add_title: 'Quick Actions',
    guide_add_desc: 'Create new buildings or clients instantly.',
    guide_settings_title: 'Settings',
    guide_settings_desc: 'Manage language and account preferences.',
    continue: 'Continue',
    close: 'Close',
    tip: 'Tip',
    help_title: 'Name of the maintenance task.',
    help_desc: 'Technical details and scope.',
    help_date: 'First execution date.',
    help_freq: 'Interval between tasks.',
    g_dash_stats: 'Real-time overview of tasks.',
    g_mgmt_search: 'Filter by city, tenant, or pro.',
    g_mgmt_add: 'Add new buildings or clients.',
    g_miss_card: 'Review proposals from professionals.',
    g_miss_date: 'Set the execution date.',
    g_miss_appr: 'Approve to create intervention.',
    g_slip_status: 'Update intervention status.',
    g_slip_notes: 'Add notes or use AI rewrite.',
    g_slip_media: 'Upload photos and docs.',
    g_slip_save: 'Save changes and notify.',
    g_maint_list: 'View active maintenance plans.',

    // Super Admin & Signup
    superAdmin: 'Super Admin',
    signup: 'Sign Up',
    pendingRequests: 'Pending Access Requests',
    createAdmin: 'Create Admin Account',
    adminList: 'System Administrators',
    signupSuccess: 'Signup request submitted successfully. Waiting for Super Admin approval.',
    noPendingRequests: 'No pending access requests.',
    createAdminSuccess: 'Admin account created successfully.',
    firstNameRequired: 'First name is required',
    lastNameRequired: 'Last name is required',
    emailRequired: 'Email is required',
    phoneRequired: 'Phone is required',
    companyRequired: 'Company name is required for Syndics',
    backToLogin: 'Back to Login',
    submitRequest: 'Submit Request',
    otpTitle: 'Verification Required',
    otpSubtitle: 'Enter the 6-digit code sent to your email.',
    verify: 'Verify Account',
    resendCode: 'Code Resend',
    otpError: 'Invalid verification code.',
    urgency: 'Urgency',
    selectUrgency: 'Select urgency...',
    attachDocuments: 'Attach Documents / Images',



    // Home Page
    features_title: 'Contractor & Admin Power',
    features_subtitle: 'Automate your intake and manage interventions with surgical precision.',
    feature_email_title: 'AI Email Ingestion',
    feature_email_desc: 'Automatically scans inbox to detect intervention requests, extracting address, urgency, and contact details.',
    feature_mission_title: 'Smart Mission Detection',
    feature_mission_desc: 'Converts emails into structured Missions. Detects urgency (Leak/Danger) and filters out spam.',
    feature_dashboard_title: 'Operational Dashboard',
    feature_dashboard_desc: 'Track Pending, Ongoing, and Delayed interventions with real-time counters and analytics.',
    feature_map_title: 'Map & Navigation',
    feature_map_desc: 'Integrated Waze/Google Maps routing for every intervention address.',
    feature_report_title: 'Auto-Report Generation',
    feature_report_desc: 'AI writing assistant helps technicians draft professional reports in seconds.',
    feature_analytics_title: 'Analytics & History',
    feature_analytics_desc: 'Monthly charts, year-over-year comparisons, and full intervention archives.',

    syndic_portal_title: 'Transparent Property Management',
    syndic_portal_desc: 'Give your property managers a dedicated portal to track every request in real-time. No more chasing for updates.',
    syndic_check_1: 'Real-time status tracking (Pending, In Progress, Completed)',
    syndic_check_2: 'Create manual intervention requests instantly',
    syndic_check_3: 'Access full history and download PDF reports',
    syndic_check_4: 'Receive automated notifications for delays or completion',

    workflow_title: 'Core Workflow',
    workflow_subtitle: 'From email reception to archived report.',
    wf_step_1_title: 'Email',
    wf_step_1_desc: 'Reception',
    wf_step_2_title: 'AI Scan',
    wf_step_2_desc: 'Analysis',
    wf_step_3_title: 'Mission',
    wf_step_3_desc: 'Validation',
    wf_step_4_title: 'Work',
    wf_step_4_desc: 'Intervention',
    wf_step_5_title: 'Report',
    wf_step_5_desc: 'Generation',
    wf_step_6_title: 'Archive',
    wf_step_6_desc: 'History',

    hero_title_1: 'Smart Renovation',
    hero_title_2: 'Interventions.',
    hero_desc: 'Streamline communication between contractors and syndics with AI-driven mission detection, automated workflows, and transparent reporting.',
    get_started: 'Get Started',
    learn_more: 'Learn More',
    access_portal: 'Access Portal',
    features: 'Features',
    workflow: 'Workflow',
    portals: 'Portals',
  },
  FR: {
    // Reports Page
    reports_title: 'Rapports d\'Intervention',
    reports_subtitle: 'Vue consolidée de tous les bons et historique.',
    latest_slips: 'Derniers Bons d\'Intervention',
    full_history: 'Historique Complet',
    filter_status: 'Filtrer par Statut',
    filter_all: 'Tous Statuts',
    filter_date_from: 'Du',
    filter_date_to: 'Au',
    search_placeholder: 'Rechercher titre, bâtiment ou adresse...',
    total: 'Total',
    load_more: 'Charger plus',
    no_interventions_yet: 'Aucune intervention.',
    create_first: 'Créer votre première intervention',
    download_pdf: 'Télécharger PDF',
    view: 'Voir',
    verify_docs: 'Vérifier les documents',
    slip_id: 'Réf Bon',
    created_at: 'Créé le',

    // ... Existing Translations ...
    period: 'Période',
    period_current_month: 'Mois en cours',
    period_3_months: '3 derniers mois',
    period_6_months: '6 derniers mois',
    period_current_year: 'Année en cours',
    kpi_missions: 'Missions',
    kpi_ongoing: 'En cours',
    kpi_delayed: 'Retardées',
    kpi_completed: 'Terminées',
    kpi_sectors: 'Interventions par secteur',
    no_data_period: 'Aucune intervention pour cette période.',
    interventions_received: 'Volume d\'interventions reçues',
    compare: 'Comparer',
    current_period: 'Période actuelle',
    previous_year: 'Année précédente',
    overview_title: 'Vue d\'ensemble',
    overview_subtitle: 'Indicateurs clés de performance.',
    delayTitle: 'Motif du retard',
    delayReasonLabel: 'Motif',
    delayDetailsLabel: 'Détails (optionnel)',
    selectReason: 'Choisir un motif...',
    delayError: 'Veuillez sélectionner un motif de retard.',
    delayDetailsPlaceholder: 'Expliquer brièvement la raison du retard…',
    improveAI_text: 'Corriger avec l’IA',
    textImproved: 'Texte amélioré',
    welcomeBack: 'Bon retour',
    manager: 'gestionnaire',
    activeSession: 'Session Active',
    logout: 'Déconnexion',
    logoutSystem: 'Déconnexion Système',
    account: 'Compte',
    currentRole: 'Rôle Actuel',
    traceability: 'Traçabilité',
    enabled: 'Activée',
    unassigned: 'Non assigné',
    missingInfo: 'Information manquante',
    dashboard: 'Tableau de bord',
    management: 'Gestion',
    ongoing: 'Interventions en cours',
    missions: 'Missions',
    missions_subtitle: 'Gérez et suivez vos demandes d\'intervention',
    status_accepted: 'Acceptées',
    status_rejected: 'Rejetées',
    no_missions: 'Aucune mission active.',
    no_pending: 'Aucune demande en attente.',
    no_accepted: 'Aucune mission acceptée pour le moment.',
    no_rejected: 'Aucune mission rejetée.',
    reports: 'Rapports',
    settings: 'Paramètres',
    help_tutorial: 'Aide & Tutoriel',

    information: 'Informations',
    memberSince: 'Membre depuis',
    statistiques: 'Statistiques',
    properties: 'Propriétés',
    security: 'Sécurité',
    privacy: 'Confidentialité',

    dash_short: 'Dash',
    emails_short: 'Emails',
    admin_short: 'Admin',

    language: 'Langue',
    live: 'En direct',
    proSelection: 'Professionnel',
    proSub: 'Gérez vos interventions et proposez des missions.',
    syndicSelection: 'Syndic / Gestionnaire',
    syndicSub: 'Demandez des interventions et suivez vos immeubles.',
    clientSelection: 'Particulier',
    clientSub: 'Suivez l\'état et l\'historique de votre bâtiment.',
    adminEntry: 'Accès Admin',
    groupMgmt: 'Gestion de Groupe',
    ecosystemDesc: 'L\'écosystème ultime du BTP pour les professionnels, syndics et propriétaires.',
    subject: 'Objet',

    addBuilding: 'Ajouter Bâtiment / Client',
    search: 'Rechercher bâtiment, locataire, ville, syndic...',
    cityOverview: 'Bâtiments par Ville',
    interventionHistory: 'Historique des interventions',
    createIntervention: 'Créer une intervention',
    createMission: 'Demande de Mission',
    sendRequest: 'Envoyer',
    createSyndic: 'Créer un syndic',
    profile: 'Profil',
    needIntervention: "Besoin d'une intervention ?",
    createRequestDesc: "Créez une demande en quelques secondes et suivez son avancement en temps réel.",
    request: 'Demande',

    myInterventions: 'Mes Interventions',

    planned: 'Missions',
    delayed: 'Retardées',
    completed: 'Terminées',
    status_pending: 'En cours',
    status_delayed: 'Retardé',
    status_completed: 'Terminé',
    totalBuildings: 'Total Bâtiments',
    activePro: 'Professionnels Actifs',
    improveAI: 'Améliorer par IA',
    optimizeAI: 'Optimiser IA',
    wait: 'Patientez...',
    working: 'Traitement...',
    post: 'Publier',
    approve: 'Approuver',
    reject: 'Rejeter',
    save: 'Enregistrer',
    cancel: 'Annuler',
    upload: 'Télécharger Document',
    sign: 'Signature Numérique',
    generateQR: 'Générer QR Code',
    back: 'Retour',
    edit: 'Éditer',
    modifier: 'MODIFIER',
    details: 'Détails',
    viewSlip: 'Voir fiche',
    validate: 'Valider',
    selectOrTypeAddress: 'Sélectionner ou saisir l\'adresse...',
    selectOrCreateSyndic: 'Sélectionner ou créer un syndic...',
    interventionTitle: 'Titre intervention',
    receptionDate: 'Date de réception',
    requiredFields: 'Champs requis',
    newBuildingAutoCreate: 'Un nouveau bâtiment sera créé',
    create: 'Créer',
    sector: 'Secteur / Catégorie',
    selectSector: 'Choisir secteur...',
    confirmDeleteTitle: 'Confirmer la suppression',
    confirmDeleteMsg: 'Êtes-vous sûr de vouloir supprimer cet élément ? Cette action est irréversible.',
    confirmDeleteMaintMsg: 'Êtes-vous sûr de vouloir supprimer ce plan d\'entretien ?',
    btnDelete: 'Supprimer',
    btnCancel: 'Annuler',
    confirmRejectTitle: 'Confirmer le rejet',
    confirmRejectMsg: 'Êtes-vous sûr de vouloir rejeter cette mission ? Cette action est irréversible.',
    btnReject: 'Rejeter la mission',
    confirmApproveMsg: 'Êtes-vous sûr de vouloir approuver cette mission ?',
    interventionDateOptional: 'Date d\'intervention (optionnel)',
    missionLabel: 'Mission',
    tabs_data: 'Données',
    tabs_history: 'Historique',
    tabs_notes: 'Notes',
    tabs_plan: 'Planif',
    tabs_docs: 'Docs',
    select_date: 'Choisir date',
    residentInfo: 'Informations Résidents',
    directContact: 'Contact Direct',
    linkedPro: 'Professionnel Lié',
    noneLinked: 'Aucun lien',
    linkedSyndic: 'Syndic Lié',
    tenant: 'Locataire',
    primaryTenant: 'Locataire Principal',
    syndic: 'Syndic',
    pro: 'Professionnel',
    contact: 'Contact',
    email: 'Email',
    phone: 'Tél',
    managerName: 'Gestionnaire',
    postNote: 'Ajouter une note',
    noCompletedInt: 'Aucune intervention terminée.',
    closedOn: 'Clôturé le',
    building_header: 'Bâtiment',
    scheduled_maintenance: 'Maintenance planifiée',
    automatic_import: 'Import automatique',
    newIntervention: 'Nouvelle Intervention',
    category: 'Catégorie',
    dateTime: 'Date et Heure',
    autoNotify: 'Notification automatique envoyée à',
    hoursBefore: '72 heures avant.',
    createPlan: 'Créer et Planifier',
    createMaintPlan: 'Créer un plan d\'entretien',
    updatePlan: 'Mettre à jour',
    saveMaintPlan: 'Enregistrer le plan',
    maintTitle: 'Titre de l\'entretien',
    smallDesc: 'Courte description',
    autoWeekBefore: 'Les interventions seront créées automatiquement 1 semaine avant chaque échéance.',
    planDuration: 'Durée du plan',
    scheduledFor: 'Planifié pendant',
    unlimited: 'Illimité',
    from: 'du',
    to: 'au',
    year_1: '1 an',
    years_2: '2 ans',
    years_3: '3 ans',
    years_5: '5 ans',
    docRepo: 'Répertoire Documentaire',
    ticketHeader: 'Bon d\'Intervention',
    description: 'Description de l\'intervention',
    adminNote: 'Note Admin',
    photos: 'Photos',
    docs: 'Documents',
    auditTrace: 'Traçabilité d\'Audit',
    intInitialized: 'Intervention initialisée le',
    updateStatus: 'Mettre à jour le statut',
    mediaAudit: 'Média et Audit',
    rescheduleDate: 'Nouvelle date estimée',
    delayedUntil: 'Retardé jusqu\'au',
    saveRegister: 'ENREGISTRER',
    saveModalTitle: 'Enregistrer la fiche',
    saveMode: 'Choisissez le mode d\'enregistrement',
    saveOnly: 'Enregistrer uniquement',
    saveEmail: 'Enregistrer et envoyer par e-mail',
    saveWhatsapp: 'Enregistrer et envoyer par WhatsApp',
    onSiteContactLabel: 'Contact sur place',
    notProvided: 'Non renseigné',
    status: 'Statut',
    autoEmailBadge: 'Créée automatiquement depuis email',
    email_template_title: 'TITRE',
    email_template_status: 'STATUT',
    email_template_desc: 'DESCRIPTION',
    email_template_contact: 'CONTACT SUR PLACE',
    email_template_note: 'NOTE ADMIN',
    email_template_delay: 'MOTIF RETARD',
    email_template_new_date: 'NOUVELLE DATE EST.',
    email_template_footer: 'Voir les détails dans l\'application Vanakel Group.',
    sendEmailError: 'Impossible d\'envoyer l\'email: aucun destinataire valide.',
    sendWhatsappError: 'Impossible d\'envoyer WhatsApp: aucun numéro lié.',
    emailClientOpened: 'Client mail ouvert.',
    mission_approved: 'Mission Approuvée',
    mission_rejected: 'Mission Rejetée',
    manual_intervention_created: 'Intervention Manuelle Créée',
    email_ingestion_mission: 'Mission Reçue par Email',
    status_change: 'Changement de Statut',
    updated: 'Mis à jour',
    maintenance_auto_title: 'Entretien (Auto-généré)',
    manual_intervention_note: 'Créé via la saisie manuelle d\'intervention',
    auto_ingestion_note: 'Créé automatiquement via ingestion email - Vérifier Syndic',
    editConfirmTitle: 'Modifier la fiche',
    editConfirmDesc: 'Voulez-vous vraiment modifier une fiche déjà existante ?',
    yesEdit: 'Oui, modifier',
    annualReport: 'Rapport Annuel',
    downloadPDF: 'Télécharger PDF',
    sendEmail: 'Envoyer Email',
    aiSummary: 'Résumé IA',
    annualMaintenance: 'Entretien annuel',
    maintenance: 'Entretien',
    frequency: 'Fréquence',
    every: 'Tous les',
    years: 'ans',
    months: 'mois',
    unit_months: 'Mois',
    unit_years: 'Ans',
    startDate: 'Date de début',
    planDate: 'Date de planification',
    reviewSave: 'Réviser & Enregistrer',
    confirm: 'Confirmer',
    planSummary: 'Résumé du plan d\'entretien',
    plannedDuration: 'Planifié pour les 5 prochaines années',
    address: 'Adresse',
    city: 'Ville',
    tenants: 'Locataires',
    add: 'Ajouter',
    firstName: 'Prénom',
    lastName: 'Nom',
    proLink: 'Lien Professionnel',
    searchPro: 'Chercher Professionnel...',
    createNewPro: 'Créer nouveau profil Pro',
    syndicLink: 'Lien Syndic',
    searchSyndic: 'Chercher Syndic...',
    createNewSyndic: 'Créer nouveau profil Syndic',
    internalNote: 'Note Interne Admin',
    createBuildingProfile: 'Créer Profil Bâtiment',
    newProfileTitle: 'Nouveau Profil',
    companyName: 'Nom de la Société',
    contactPerson: 'Personne de Contact',
    contactFirstName: 'Prénom',
    contactLastName: 'Nom',
    gsm: 'GSM / Tél',
    mobileNumber: 'Numéro Mobile',
    landline: 'Ligne Fixe',
    emailAddress: 'Adresse Email',
    businessAddress: 'Adresse Professionnelle',
    createProfile: 'Créer Profil',
    contact_name: 'Nom',
    contact_gsm: 'GSM / Tél',
    contact_email_opt: 'Email (Optionnel)',
    gestion_title: 'Gestion',
    gestion_subtitle: 'Vue d\'ensemble des propriétés avec interventions terminées.',
    all_syndics: 'Tous les syndics',
    no_properties_title: 'Aucune propriété trouvée',
    no_properties_desc: 'Aucune propriété ne correspond à vos filtres ou aucune intervention terminée n\'existe encore.',
    syndic_contact_title: 'Contact Syndic',
    no_syndic_linked: 'Non lié à un syndic spécifique.',
    history_title: 'Historique des Interventions',
    no_history_found: 'Aucun historique d\'intervention trouvé pour cette propriété.',
    intervention_slip_doc: 'Bon d\'intervention',
    email_logs_title: 'Journaux d\'Ingestion Email',
    email_logs_empty: 'Aucun journal disponible. Lancez l\'ingestion manuellement.',
    ingest_button_idle: 'Lancer l\'ingestion Email (Simulation)',
    ingest_button_working: 'Traitement en cours...',
    extracted_data: 'Données extraites',
    guide_welcome_title: 'Bienvenue chez Vanakel Group',
    guide_welcome_desc: 'Votre écosystème de gestion professionnelle.',
    guide_nav_title: 'Navigation',
    guide_nav_desc: 'Accédez au tableau de bord, bâtiments et missions ici.',
    guide_add_title: 'Actions Rapides',
    guide_add_desc: 'Créez instantanément de nouveaux bâtiments ou clients.',
    guide_settings_title: 'Paramètres',
    guide_settings_desc: 'Gérez la langue et les préférences du compte.',
    continue: 'Continuer',
    close: 'Fermer',
    tip: 'Astuce',
    help_title: 'Nom de la tâche d\'entretien.',
    help_desc: 'Détails techniques et périmètre.',
    help_date: 'Première date d\'exécution.',
    help_freq: 'Intervalle entre les tâches.',
    g_dash_stats: 'Vue d\'ensemble en temps réel.',
    g_mgmt_search: 'Filtrer par ville, locataire ou pro.',
    g_mgmt_add: 'Ajouter bâtiments ou clients.',
    g_miss_card: 'Revoir les propositions des pros.',
    g_miss_date: 'Définir la date d\'exécution.',
    g_miss_appr: 'Approuver pour créer l\'intervention.',
    g_slip_status: 'Mettre à jour le statut.',
    g_slip_notes: 'Ajouter notes ou utiliser l\'IA.',
    g_slip_media: 'Télécharger photos et docs.',
    g_slip_save: 'Sauvegarder',
    g_maint_list: 'Voir les plans actifs.',

    // Super Admin & Signup
    superAdmin: 'Super Admin',
    signup: 'S\'inscrire',
    pendingRequests: 'Demandes d\'Accès en Attente',
    createAdmin: 'Créer un Compte Admin',
    adminList: 'Administrateurs Système',
    signupSuccess: 'Demande d\'inscription envoyée avec succès. En attente de validation.',
    noPendingRequests: 'Aucune demande en attente.',
    createAdminSuccess: 'Compte administrateur créé avec succès.',
    firstNameRequired: 'Le prénom est requis',
    lastNameRequired: 'Le nom est requis',
    emailRequired: 'L\'email est requis',
    phoneRequired: 'Le téléphone est requis',
    companyRequired: 'Le nom de la société est requis pour les Syndics',
    backToLogin: 'Retour à la connexion',
    submitRequest: 'Envoyer la demande',
    otpTitle: 'Vérification Requise',
    otpSubtitle: 'Entrez le code à 6 chiffres envoyé à votre adresse e-mail.',
    verify: 'Vérifier le compte',
    resendCode: 'Renvoyer le code',
    otpError: 'Code de vérification invalide.',
    urgency: 'Urgence',
    selectUrgency: 'Choisir l\'urgence...',
    attachDocuments: 'Joindre des documents / images',



    // Home Page
    features_title: 'Puissance Admin & Entrepreneur',
    features_subtitle: 'Automatisez votre réception et gérez les interventions avec une précision chirurgicale.',
    feature_email_title: 'Ingestion Email IA',
    feature_email_desc: 'Scanne automatiquement la boîte de réception pour détecter les demandes, extrayant adresse, urgence et contacts.',
    feature_mission_title: 'Détection de Mission Intelligente',
    feature_mission_desc: 'Convertit les emails en Missions structurées. Détecte l\'urgence (Fuite/Danger) et filtre le spam.',
    feature_dashboard_title: 'Tableau de Bord Opérationnel',
    feature_dashboard_desc: 'Suivez les interventions en attente, en cours et retardées avec des compteurs et analyses en temps réel.',
    feature_map_title: 'Carte & Navigation',
    feature_map_desc: 'Itinéraires Waze/Google Maps intégrés pour chaque adresse d\'intervention.',
    feature_report_title: 'Génération de Rapport Auto',
    feature_report_desc: 'L\'assistant d\'écriture IA aide les techniciens à rédiger des rapports professionnels en quelques secondes.',
    feature_analytics_title: 'Analyses & Historique',
    feature_analytics_desc: 'Graphiques mensuels, comparaisons annuelles et archives complètes des interventions.',

    syndic_portal_title: 'Gestion Immobilière Transparente',
    syndic_portal_desc: 'Offrez à vos gestionnaires un portail dédié pour suivre chaque demande en temps réel. Plus besoin de relancer.',
    syndic_check_1: 'Suivi de statut en temps réel (En attente, En cours, Terminé)',
    syndic_check_2: 'Créer des demandes d\'intervention manuelles instantanément',
    syndic_check_3: 'Accéder à l\'historique complet et télécharger les rapports PDF',
    syndic_check_4: 'Recevoir des notifications automatisées pour les retards ou la complétion',

    workflow_title: 'Flux de Travail Central',
    workflow_subtitle: 'De la réception de l\'email au rapport archivé.',
    wf_step_1_title: 'Email',
    wf_step_1_desc: 'Réception',
    wf_step_2_title: 'Scan IA',
    wf_step_2_desc: 'Analyse',
    wf_step_3_title: 'Mission',
    wf_step_3_desc: 'Validation',
    wf_step_4_title: 'Travail',
    wf_step_4_desc: 'Intervention',
    wf_step_5_title: 'Rapport',
    wf_step_5_desc: 'Génération',
    wf_step_6_title: 'Archive',
    wf_step_6_desc: 'Historique',

    hero_title_1: 'Interventions de',
    hero_title_2: 'Rénovation Intelligentes.',
    hero_desc: 'Fluidifiez la communication entre entrepreneurs et syndics grâce à la détection de mission par IA, des flux automatisés et un reporting transparent.',
    get_started: 'Commencer',
    learn_more: 'En savoir plus',
    access_portal: 'Accéder au Portail',
    features: 'Fonctionnalités',
    workflow: 'Flux',
    portals: 'Portails',
  },
  NL: {
    // Reports Page
    reports_title: 'Interventierapporten',
    reports_subtitle: 'Geconsolideerd overzicht van alle interventiebonnen en geschiedenis.',
    latest_slips: 'Laatste Interventiebonnen',
    full_history: 'Volledige Geschiedenis',
    filter_status: 'Filter op Status',
    filter_all: 'Alle Statussen',
    filter_date_from: 'Van',
    filter_date_to: 'Tot',
    search_placeholder: 'Zoek titel, gebouw of adres...',
    total: 'Totaal',
    load_more: 'Meer laden',
    no_interventions_yet: 'Nog geen interventies.',
    create_first: 'Maak uw eerste interventie aan',
    download_pdf: 'PDF Downloaden',
    view: 'Bekijken',
    verify_docs: 'Documenten nakijken',
    slip_id: 'Bon Ref',
    created_at: 'Aangemaakt op',

    // ... Existing Translations ...
    period: 'Periode',
    period_current_month: 'Huidige maand',
    period_3_months: 'Laatste 3 maanden',
    period_6_months: 'Laatste 6 maanden',
    period_current_year: 'Huidig jaar',
    kpi_missions: 'Missies',
    kpi_ongoing: 'Lopend',
    kpi_delayed: 'Vertraagd',
    kpi_completed: 'Voltooid',
    kpi_sectors: 'Interventies per sector',
    no_data_period: 'Geen interventies voor deze periode.',
    interventions_received: 'Ontvangen interventies',
    compare: 'Vergelijken',
    current_period: 'Huidige periode',
    previous_year: 'Vorig jaar',
    overview_title: 'Overzicht',
    overview_subtitle: 'Belangrijkste prestatie-indicatoren.',
    delayTitle: 'Reden van vertraging',
    delayReasonLabel: 'Reden',
    delayDetailsLabel: 'Details (optioneel)',
    selectReason: 'Selecteer een reden...',
    delayError: 'Selecteer een reden voor vertraging.',
    delayDetailsPlaceholder: 'Geef kort de reden van de vertraging…',
    improveAI_text: 'Corrigeren met AI',
    textImproved: 'Tekst verbeterd',
    welcomeBack: 'Welkom terug',
    manager: 'beheerder',
    activeSession: 'Actieve Sessie',
    logout: 'Afmelden',
    logoutSystem: 'Systeem Afmelden',
    account: 'Account',
    currentRole: 'Huidige Rol',
    traceability: 'Traceerbaarheid',
    enabled: 'Ingeschakeld',
    unassigned: 'Niet toegewezen',
    missingInfo: 'Ontbrekende informatie',
    dashboard: 'Dashboard',
    management: 'Beheer',
    ongoing: 'Lopende Interventies',
    missions: 'Missies',
    missions_subtitle: 'Beheer en volg uw serviceaanvragen voor gebouwen',
    status_accepted: 'Geaccepteerd',
    status_rejected: 'Geweigerd',
    no_missions: 'Geen actieve missies.',
    no_pending: 'Geen wachtende aanvragen.',
    no_accepted: 'Nog geen geaccepteerde missies.',
    no_rejected: 'Geen geweigerde missies.',
    reports: 'Rapporten',
    settings: 'Instellingen',
    help_tutorial: 'Help & Tutorial',

    information: 'Informatie',
    memberSince: 'Lid sinds',
    statistiques: 'Statistieken',
    properties: 'Eigendommen',
    security: 'Beveiliging',
    privacy: 'Privacy',

    dash_short: 'Dash',
    emails_short: 'E-mails',
    admin_short: 'Admin',

    language: 'Taal',
    live: 'Live',
    proSelection: 'Professioneel',
    proSub: 'Beheer interventies en stel missies voor.',
    syndicSelection: 'Syndicus / Beheerder',
    syndicSub: 'Vraag interventies aan en volg gebouwen op.',
    clientSelection: 'Particulier',
    clientSub: 'Volg de status en geschiedenis van uw gebouw.',
    adminEntry: 'Admin Toegang',
    groupMgmt: 'Groepsbeheer',
    ecosystemDesc: 'Het ultieme ecosysteem voor bouwbeheer voor professionals, syndici en eigenaars.',
    subject: 'Onderwerp',

    addBuilding: 'Gebouw / Klant Toevoegen',
    search: 'Zoek gebouw, huurder, stad, syndicus...',
    cityOverview: 'Gebouwen per Stad',
    interventionHistory: 'Interventiegeschiedenis',
    createIntervention: 'Interventie aanmaken',
    createMission: 'Opdrachtaanvraag',
    sendRequest: 'Verzenden',
    createSyndic: 'Syndicus aanmaken',
    profile: 'Profiel',
    needIntervention: 'Interventie nodig?',
    createRequestDesc: 'Maak binnen enkele seconden een aanvraag aan en volg de voortgang in realtime.',
    request: 'Aanvraag',

    myInterventions: 'Mijn Interventies',

    planned: 'Missies',
    delayed: 'Vertraagd',
    completed: 'Voltooid',
    status_pending: 'In uitvoering',
    status_delayed: 'Vertraagd',
    status_completed: 'Voltooid',
    totalBuildings: 'Totaal Gebouwen',
    activePro: 'Actieve Professionals',
    improveAI: 'Verbeter met AI',
    optimizeAI: 'Optimaliseer met AI',
    wait: 'Wachten...',
    working: 'Verwerken...',
    post: 'Plaatsen',
    approve: 'Goedkeuren',
    reject: 'Afwijzen',
    save: 'Opslaan',
    cancel: 'Annuleren',
    upload: 'Document Uploaden',
    sign: 'Digitale Handtekening',
    generateQR: 'QR-code Genereren',
    back: 'Terug',
    edit: 'Bewerken',
    modifier: 'WIJZIGEN',
    details: 'Details',
    viewSlip: 'Bekijk fiche',
    validate: 'Valideren',
    selectOrTypeAddress: 'Selecteer of typ adres...',
    selectOrCreateSyndic: 'Selecteer of maak syndicus...',
    interventionTitle: 'Titel interventie',
    receptionDate: 'Ontvangstdatum',
    requiredFields: 'Verplichte velden',
    newBuildingAutoCreate: 'Nieuw gebouw wordt aangemaakt',

    // Home Page
    features_title: 'Aannemer & Admin Kracht',
    features_subtitle: 'Automatiseer uw intake en beheer interventies met chirurgische precisie.',
    feature_email_title: 'AI E-mail Verwerking',
    feature_email_desc: 'Scant automatisch inbox om interventieaanvragen te detecteren, extraheert adres, urgentie en contactgegevens.',
    feature_mission_title: 'Slimme Missie Detectie',
    feature_mission_desc: 'Zet e-mails om in gestructureerde Missies. Detecteert urgentie (Lek/Gevaar) en filtert spam.',
    feature_dashboard_title: 'Operationeel Dashboard',
    feature_dashboard_desc: 'Volg wachtende, lopende en vertraagde interventies met realtime tellers en analyses.',
    feature_map_title: 'Kaart & Navigatie',
    feature_map_desc: 'Geïntegreerde Waze/Google Maps routes voor elk interventieadres.',
    feature_report_title: 'Auto-Rapport Generatie',
    feature_report_desc: 'AI schrijfassistent helpt technici professionele rapporten op te stellen in seconden.',
    feature_analytics_title: 'Analyses & Geschiedenis',
    feature_analytics_desc: 'Maandelijkse grafieken, jaarvergelijkingen en volledige interventiearchieven.',

    syndic_portal_title: 'Transparant Vastgoedbeheer',
    syndic_portal_desc: 'Geef uw beheerders een eigen portaal om elke aanvraag in realtime te volgen. Geen updates meer najagen.',
    syndic_check_1: 'Realtime statusopvolging (In wacht, Bezig, Voltooid)',
    syndic_check_2: 'Maak direct handmatige interventieaanvragen aan',
    syndic_check_3: 'Toegang tot volledige geschiedenis en PDF-rapporten downloaden',
    syndic_check_4: 'Ontvang automatische meldingen voor vertragingen of voltooiing',

    workflow_title: 'Kern Workflow',
    workflow_subtitle: 'Van e-mailontvangst tot gearchiveerd rapport.',
    wf_step_1_title: 'E-mail',
    wf_step_1_desc: 'Ontvangst',
    wf_step_2_title: 'AI Scan',
    wf_step_2_desc: 'Analyse',
    wf_step_3_title: 'Missie',
    wf_step_3_desc: 'Validatie',
    wf_step_4_title: 'Werk',
    wf_step_4_desc: 'Interventie',
    wf_step_5_title: 'Rapport',
    wf_step_5_desc: 'Generatie',
    wf_step_6_title: 'Archief',
    wf_step_6_desc: 'Geschiedenis',

    hero_title_1: 'Slimme Renovatie',
    hero_title_2: 'Interventies.',
    hero_desc: 'Stroomlijn communicatie tussen aannemers en syndici met AI-gestuurde missiedetectie, geautomatiseerde workflows en transparante rapportage.',
    get_started: 'Aan de slag',
    learn_more: 'Meer info',
    access_portal: 'Toegang Portaal',
    features: 'Functies',
    workflow: 'Workflow',
    portals: 'Portalen',
    create: 'Aanmaken',
    sector: 'Sector / Categorie',
    selectSector: 'Selecteer sector...',
    confirmDeleteTitle: 'Verwijderen bevestigen',
    confirmDeleteMsg: 'Weet u zeker dat u dit element wilt verwijderen? Deze actie is onomkeerbaar.',
    confirmDeleteMaintMsg: 'Weet u zeker dat u dit onderhoudsplan wilt verwijderen?',
    btnDelete: 'Verwijderen',
    btnCancel: 'Annuleren',
    confirmRejectTitle: 'Weigering bevestigen',
    confirmRejectMsg: 'Weet u zeker dat u deze opdracht wilt weigeren? Deze actie is onomkeerbaar.',
    btnReject: 'Opdracht weigeren',
    confirmApproveMsg: 'Weet u zeker dat u deze opdracht wilt goedkeuren?',
    interventionDateOptional: 'Interventiedatum (optioneel)',
    missionLabel: 'Opdracht',
    tabs_data: 'Gegevens',
    tabs_history: 'Historiek',
    tabs_notes: 'Notities',
    tabs_plan: 'Plan',
    tabs_docs: 'Docs',
    select_date: 'Kies datum',
    residentInfo: 'Bewonersinformatie',
    directContact: 'Direct Contact',
    linkedPro: 'Gekoppelde Professional',
    noneLinked: 'Geen koppeling',
    linkedSyndic: 'Gekoppelde Syndicus',
    tenant: 'Huurder',
    primaryTenant: 'Hoofdhuurder',
    syndic: 'Syndicus',
    pro: 'Professional',
    contact: 'Contact',
    email: 'E-mail',
    phone: 'Tel',
    managerName: 'Beheerder',
    postNote: 'Notitie plaatsen',
    noCompletedInt: 'Nog geen voltooide interventies.',
    closedOn: 'Gesloten op',
    building_header: 'Gebouw',
    scheduled_maintenance: 'Gepland onderhoud',
    automatic_import: 'Automatische import',
    newIntervention: 'Nieuwe Interventie',
    category: 'Categorie',
    dateTime: 'Datum & Tijd',
    autoNotify: 'Automatische melding wordt verzonden naar',
    hoursBefore: '72 uur van tevoren.',
    createPlan: 'Maken & Plannen',
    createMaintPlan: 'Onderhoudsplan maken',
    updatePlan: 'Plan bijwerken',
    saveMaintPlan: 'Onderhoudsplan opslaan',
    maintTitle: 'Onderhoudstitel',
    smallDesc: 'Korte beschrijving',
    autoWeekBefore: 'Interventies worden automatisch 1 week voor elke vervaldatum aangemaakt.',
    planDuration: 'Duur van het plan',
    scheduledFor: 'Gepland voor',
    unlimited: 'Onbeperkt',
    from: 'van',
    to: 'tot',
    year_1: '1 jaar',
    years_2: '2 jaar',
    years_3: '3 jaar',
    years_5: '5 jaar',
    docRepo: 'Documentenarchief',
    ticketHeader: 'Interventiebon',
    description: 'Beschrijving interventie',
    adminNote: 'Admin Notitie',
    photos: 'Foto\'s',
    docs: 'Documenten',
    auditTrace: 'Audit Traceerbaarheid',
    intInitialized: 'Interventie gestart op',
    updateStatus: 'Status bijwerken',
    mediaAudit: 'Media & Audit',
    rescheduleDate: 'Nieuwe geschatte datum',
    delayedUntil: 'Vertraagd tot',
    saveRegister: 'REGISTREREN',
    saveModalTitle: 'Fiche opslaan',
    saveMode: 'Kies opslagmodus',
    saveOnly: 'Alleen opslaan',
    saveEmail: 'Opslaan & e-mail verzenden',
    saveWhatsapp: 'Opslaan & WhatsApp verzenden',
    onSiteContactLabel: 'Contact ter plaatse',
    notProvided: 'Niet ingevuld',
    status: 'Status',
    autoEmailBadge: 'Automatisch aangemaakt via e-mail',
    email_template_title: 'TITEL',
    email_template_status: 'STATUS',
    email_template_desc: 'BESCHRIJVING',
    email_template_contact: 'CONTACT TER PLAATSE',
    email_template_note: 'ADMIN NOTITIE',
    email_template_delay: 'REDEN VERTRAGING',
    email_template_new_date: 'NIEUWE GESCHATTE DATUM',
    email_template_footer: 'Bekijk details in de Vanakel Group applicatie.',
    sendEmailError: 'Kan e-mail niet verzenden: geen geldige ontvangers.',
    sendWhatsappError: 'Kan WhatsApp niet verzenden: geen nummer gekoppeld.',
    emailClientOpened: 'E-mailclient geopend.',
    mission_approved: 'Missie Goedgekeurd',
    mission_rejected: 'Missie Afgewezen',
    manual_intervention_created: 'Handmatige Interventie Aangemaakt',
    email_ingestion_mission: 'Missie Ontvangen via E-mail',
    status_change: 'Statuswijziging',
    updated: 'Bijgewerkt',
    maintenance_auto_title: 'Onderhoud (Automatisch gegenereerd)',
    manual_intervention_note: 'Aangemaakt via handmatige interventie-invoer',
    auto_ingestion_note: 'Automatisch aangemaakt via e-mailopname - Controleer Syndicus',
    editConfirmTitle: 'Fiche bewerken',
    editConfirmDesc: 'Wilt u echt een bestaande fiche bewerken?',
    yesEdit: 'Ja, bewerken',
    annualReport: 'Jaarverslag',
    downloadPDF: 'Download PDF',
    sendEmail: 'E-mail Verzenden',
    aiSummary: 'AI Samenvatting',
    annualMaintenance: 'Jaarlijks onderhoud',
    maintenance: 'Onderhoud',
    frequency: 'Frequentie',
    every: 'Elke',
    years: 'jaar',
    months: 'maanden',
    unit_months: 'Maanden',
    unit_years: 'Jaren',
    startDate: 'Startdatum',
    planDate: 'Planningsdatum',
    reviewSave: 'Controleren & Opslaan',
    confirm: 'Bevestigen',
    planSummary: 'Samenvatting onderhoudsplan',
    plannedDuration: 'Gepland voor de komende 5 jaar',
    address: 'Adres',
    city: 'Stad',
    tenants: 'Huurders',
    add: 'Toevoegen',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    proLink: 'Link Professional',
    searchPro: 'Zoek Professional...',
    createNewPro: 'Nieuw Pro profiel maken',
    syndicLink: 'Link Syndicus',
    searchSyndic: 'Zoek Syndicus...',
    createNewSyndic: 'Nieuw Syndicus profiel maken',
    internalNote: 'Interne Admin Notitie',
    createBuildingProfile: 'Gebouwprofiel Maken',
    newProfileTitle: 'Nieuw Profiel',
    companyName: 'Bedrijfsnaam',
    contactPerson: 'Contactpersoon',
    contactFirstName: 'Voornaam',
    contactLastName: 'Achternaam',
    gsm: 'Mobiel / GSM',
    mobileNumber: 'Mobiel Nummer',
    landline: 'Vaste Lijn',
    emailAddress: 'E-mailadres',
    businessAddress: 'Zakelijk Adres',
    createProfile: 'Profiel Maken',
    contact_name: 'Naam',
    contact_gsm: 'GSM / Tel',
    contact_email_opt: 'E-mail (Optioneel)',
    gestion_title: 'Beheer',
    gestion_subtitle: 'Overzicht van alle eigendommen met voltooide interventies.',
    all_syndics: 'Alle Syndici',
    no_properties_title: 'Geen eigendommen gevonden',
    no_properties_desc: 'Geen eigendommen voldeden aan uw filters of er zijn nog geen voltooide interventies.',
    syndic_contact_title: 'Syndicus Contact',
    no_syndic_linked: 'Niet gekoppeld aan een specifieke syndicus.',
    history_title: 'Interventiegeschiedenis',
    no_history_found: 'Geen voltooide interventies gevonden voor dit eigendom.',
    intervention_slip_doc: 'Interventiebon',
    email_logs_title: 'E-mail Opname Logboeken',
    email_logs_empty: 'Nog geen e-mail logboeken beschikbaar. Start de opname handmatig.',
    ingest_button_idle: 'E-mail Opname Uitvoeren (Simulatie)',
    ingest_button_working: 'Bezig met verwerken...',
    extracted_data: 'Geëxtraheerde gegevens',
    guide_welcome_title: 'Welkom bij Vanakel Group',
    guide_welcome_desc: 'Uw professionele beheer ecosysteem.',
    guide_nav_title: 'Navigatie',
    guide_nav_desc: 'Toegang tot Dashboard, Gebouwen en Missies.',
    guide_add_title: 'Snelle Acties',
    guide_add_desc: 'Maak direct nieuwe gebouwen of klanten aan.',
    guide_settings_title: 'Instellingen',
    guide_settings_desc: 'Beheer taal en accountvoorkeuren.',
    continue: 'Doorgaan',
    close: 'Sluiten',
    tip: 'Tip',
    help_title: 'Naam van de onderhoudstaak.',
    help_desc: 'Technische details en omvang.',
    help_date: 'Eerste uitvoeringsdatum.',
    help_freq: 'Interval tussen taken.',
    g_dash_stats: 'Real-time overzicht taken.',
    g_mgmt_search: 'Filter op stad, huurder of pro.',
    g_mgmt_add: 'Nieuwe gebouwen toevoegen.',
    g_miss_card: 'Bekijk voorstellen van pro\'s.',
    g_miss_date: 'Stel de uitvoeringsdatum in.',
    g_miss_appr: 'Goedkeuren voor interventie.',
    g_slip_status: 'Update status.',
    g_slip_notes: 'Notities of AI-herschrijven.',
    g_slip_media: 'Upload foto\'s en docs.',
    g_slip_save: 'Opslaan en melden.',
    g_maint_list: 'Bekijk actieve plannen.',

    // Super Admin & Signup
    superAdmin: 'Super Admin',
    signup: 'Registreren',
    pendingRequests: 'Wachtende Toegangsaanvragen',
    createAdmin: 'Admin account aanmaken',
    adminList: 'Systeembeheerders',
    signupSuccess: 'Registratieaanvraag succesvol ingediend. Wacht op goedkeuring door de Super Admin.',
    noPendingRequests: 'Geen wachtende aanvragen.',
    createAdminSuccess: 'Admin account succesvol aangemaakt.',
    firstNameRequired: 'Voornaam is verplicht',
    lastNameRequired: 'Achternaam is verplicht',
    emailRequired: 'E-mail is verplicht',
    phoneRequired: 'Telefoon is verplicht',
    companyRequired: 'Bedrijfsnaam is verplicht voor Syndici',
    backToLogin: 'Terug naar inloggen',
    submitRequest: 'Aanvraag indienen',
    otpTitle: 'Verificatie Vereist',
    otpSubtitle: 'Voer de 6-cijferige code in die naar uw e-mail is verzonden.',
    verify: 'Account Verifiëren',
    resendCode: 'Code Opnieuw Verzenden',
    otpError: 'Ongeldige verificatiecode.',
    urgency: 'Urgentie',
    selectUrgency: 'Kies urgentie...',
    attachDocuments: 'Documenten / afbeeldingen bijvoegen',


  }
};
